import Head from "next/head";
import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
} from "@chakra-ui/react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";

import { useWallet } from "@cosmos-kit/react";
import { WalletStatus } from "@cosmos-kit/core";

import { chainEndpoint, cw20ContractAddress, dependencies, messagingContractAddress, products } from "../config";
import {
  Product,
  Dependency,
  WalletSection,
  handleChangeColorModeValue,
  HackCw20,
} from "../components";
import { useHackCw20Balance } from "../hooks/use-hack-cw20-balance";
import { useState } from "react";
import { MessagingQueryClient } from "../codegen/Messaging.client";
import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";

const library = {
  title: "Telescope",
  text: "telescope",
  href: "https://github.com/cosmology-tech/interchain",
};

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  const { walletStatus } = useWallet();
  const { balance } = useHackCw20Balance(cw20ContractAddress);

  const[greeting, setGreeting] = useState('');
  const messagingQueryClient = async () => {
    const cosmwasmclient = await CosmWasmClient.connect(chainEndpoint);
    return new MessagingQueryClient(cosmwasmclient, messagingContractAddress);
  };


  const getAndSetGreeting = async () => {
    const greeting
  }

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Simple Messaging on Cudos</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === "light" ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
      </Flex>
      <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: "3xl", sm: "4xl", md: "5xl" }}
          fontWeight="extrabold"
          mb={3}
        >
          Simple Messaging App on Cudos
        </Heading>
        <Heading
          as="h1"
          fontWeight="bold"
          fontSize={{ base: "2xl", sm: "3xl", md: "4xl" }}
        >
          <Text as="span">
            {/* greeting */}
          </Text>
        </Heading>
      </Box>

      <WalletSection />

      <Box mb={3}>
        <Divider />
      </Box>
      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
        <Text>Built with</Text>
        <Link
          href="https://cosmology.tech/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
      </Stack>
    </Container>
  );
}
