/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Messaging.types";
import * as _1 from "./Messaging.client";
export namespace contracts {
  export const Messaging = { ..._0,
    ..._1
  };
}